from fastapi import FastAPI, Header, Query
from fastapi.middleware.cors import CORSMiddleware
from apscheduler.schedulers.background import BackgroundScheduler
from contextlib import asynccontextmanager
import requests, threading, time, os, json, csv, traceback
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from io import StringIO
import builtins

# ── In-memory log buffer ───────────────────────────────────────────────────────
_log_buffer = []
_log_lock   = threading.Lock()
_orig_print = builtins.print

def _patched_print(*args, **kwargs):
    msg = " ".join(str(a) for a in args)
    ts  = datetime.now(ZoneInfo("Asia/Kolkata")).strftime("%H:%M:%S")
    with _log_lock:
        _log_buffer.append(f"[{ts}] {msg}")
        if len(_log_buffer) > 500:  # keep last 500 lines
            _log_buffer.pop(0)
    _orig_print(*args, **kwargs)

builtins.print = _patched_print

DHAN_BASE = "https://api.dhan.co"
IST       = ZoneInfo("Asia/Kolkata")
SELF_URL  = os.getenv("RENDER_EXTERNAL_URL", "").rstrip("/")

CREDS = {
    "client_id":    os.getenv("DHAN_CLIENT_ID", ""),
    "access_token": os.getenv("DHAN_ACCESS_TOKEN", ""),
}

cache = {
    "data": [], "updated_at": None, "status": "idle",
    "count": 0, "errors": [], "progress": 0, "total": 0,
    "symbol_source": "none", "market_open": False, "debug": {},
}
SYMBOLS = []
_lock   = threading.Lock()

# ── Security IDs ──────────────────────────────────────────────────────────────
# These are loaded from correct_ids.json (generated by fetch_ids.py weekly)
# VERIFIED_IDS is kept as emergency fallback only — do not add stocks here
# The CSV fetch_ids.py workflow is the authoritative source
VERIFIED_IDS = {}  # populated from correct_ids.json or CSV on startup

def ist_now(): return datetime.now(IST)
def is_market_open():
    n = ist_now()
    if n.weekday() >= 5: return False
    return n.replace(hour=9,minute=15,second=0,microsecond=0) <= n <= \
           n.replace(hour=15,minute=30,second=0,microsecond=0)

# ── Symbol loading ─────────────────────────────────────────────────────────────
DISK_PATH = "/tmp/dhan_symbols.json"

def save_symbols():
    try:
        with open(DISK_PATH,"w") as f:
            json.dump({"symbols":SYMBOLS,"source":cache["symbol_source"],
                       "at":ist_now().strftime("%H:%M IST")}, f)
    except: pass

def load_symbols_disk():
    global SYMBOLS
    # First try correct_ids.json (generated by fetch_ids.py — most accurate)
    for path in ["correct_ids.json", DISK_PATH]:
        try:
            with open(path) as f:
                d = json.load(f)
            # correct_ids.json is a flat {symbol: id} dict
            if isinstance(d, dict) and not d.get("symbols"):
                syms = [{"symbol": s, "security_id": sid, "exchange": "NSE"}
                        for s, sid in d.items()]
                if len(syms) >= 100:
                    SYMBOLS = syms
                    cache["symbol_source"] = "correct_ids_json"
                    print(f"[sym] loaded {len(SYMBOLS)} from {path}")
                    return True
            # DISK_PATH format: {"symbols": [...], ...}
            elif len(d.get("symbols", [])) >= 100:
                SYMBOLS = d["symbols"]
                cache["symbol_source"] = "disk"
                print(f"[sym] loaded {len(SYMBOLS)} from {path}")
                return True
        except Exception as e:
            pass
    return False

def load_symbols_verified():
    """Load from correct_ids.json — generated by fetch_ids.py weekly workflow."""
    global SYMBOLS, VERIFIED_IDS
    # Try correct_ids.json first (most up to date)
    for path in ["correct_ids.json"]:
        try:
            with open(path) as f:
                d = json.load(f)
            if isinstance(d, dict) and len(d) >= 50:
                SYMBOLS = [{"symbol": s, "security_id": sid, "exchange": "NSE"}
                           for s, sid in sorted(d.items())]
                VERIFIED_IDS = dict(d)
                cache["symbol_source"] = "correct_ids_json"
                print(f"[sym] verified: loaded {len(SYMBOLS)} from {path}")
                return True
        except: pass
    # If correct_ids.json missing, try CSV
    print(f"[sym] correct_ids.json not found — will try CSV")
    return False

def load_symbols_csv(tok=""):
    """Try to get fresh IDs from Dhan CSV. Updates VERIFIED_IDS if successful."""
    global SYMBOLS, VERIFIED_IDS
    for url in ["https://images.dhan.co/api-data/api-scrip-master.csv",
                "https://images.dhan.co/api-data/api-scrip-master-detailed.csv"]:
        try:
            print(f"[sym] trying {url.split('/')[-1]}...")
            r = requests.get(url, timeout=45)
            print(f"[sym]   {r.status_code} len={len(r.text)}")
            if r.status_code != 200 or len(r.text) < 10000: continue
            eq, fno = _parse_csv(r.text)
            if len(eq) < 100: continue
            # Use CSV FNO list as authoritative — removes delisted stocks automatically
            if len(fno) >= 50:
                all_names = fno  # CSV is source of truth
                print(f"[sym] using CSV FNO list: {len(fno)} symbols")
            else:
                all_names = set(VERIFIED_IDS.keys())  # fallback
                print(f"[sym] CSV FNO list small ({len(fno)}) — using verified fallback")
            matched = [{"symbol":s,"security_id":eq[s],"exchange":"NSE"}
                       for s in sorted(all_names) if s in eq]
            if len(matched) < 100: continue
            SYMBOLS = matched
            VERIFIED_IDS = {s["symbol"]:s["security_id"] for s in SYMBOLS}
            cache["symbol_source"] = "csv"
            save_symbols()
            print(f"[sym] csv: {len(SYMBOLS)} symbols ✓")
            return True
        except Exception as e:
            print(f"[sym]   error: {e}")
    return False

def _find_col(header, *keywords):
    """Return first column index whose header contains any keyword."""
    for i, h in enumerate(header):
        for kw in keywords:
            if kw in h:
                return i
    return None

def _parse_csv(text):
    eq, fno = {}, set()
    reader = csv.reader(StringIO(text))
    header = None
    exch_i = seg_i = sym_i = id_i = inst_i = series_i = undl_i = None
    for row in reader:
        if header is None:
            header   = [h.strip().upper() for h in row]
            exch_i   = _find_col(header, "SEM_EXM_EXCH_ID", "EXCH_ID", "EXCHANGE")
            seg_i    = _find_col(header, "SEM_SEGMENT", "EXCH_SEG", "SEGMENT")
            sym_i    = _find_col(header, "SEM_TRADING_SYMBOL", "TRADING_SYMBOL")
            id_i     = _find_col(header, "SEM_SMST_SECURITY_ID", "SECURITY_ID", "SCRIP_ID", "SM_SYMBOL_ID")
            inst_i   = _find_col(header, "SEM_INSTRUMENT_NAME", "INSTRUMENT", "SEM_INSTRUMENT")
            series_i = _find_col(header, "SEM_SERIES", "SERIES")
            undl_i   = _find_col(header, "SM_SYMBOL_NAME", "SYMBOL_NAME")
            if None in (sym_i, id_i): break
            continue
        max_i = max(c for c in (exch_i, seg_i, sym_i, id_i, inst_i, series_i, undl_i) if c is not None)
        if len(row) <= max_i: continue
        sym    = row[sym_i].strip()
        seg    = row[seg_i].strip().upper()    if seg_i    is not None else ""
        exch   = row[exch_i].strip().upper()   if exch_i   is not None else ""
        inst   = row[inst_i].strip().upper()   if inst_i   is not None else ""
        series = row[series_i].strip().upper() if series_i is not None else ""
        undl   = row[undl_i].strip()           if undl_i   is not None and len(row) > undl_i else ""
        if not sym and not undl: continue
        is_nse_eq = (
            (exch == "NSE" and seg == "E" and series == "EQ") or
            seg in ("NSE_EQ", "NSE EQ", "NSEEQ") or
            (seg.startswith("NSE") and "EQ" in seg)
        )
        is_nse_fno = (
            (exch == "NSE" and inst in ("FUTSTK", "OPTSTK")) or
            "FNO" in seg or "NSE_FO" in seg
        )
        if is_nse_eq and sym not in eq:
            try: eq[sym] = str(int(float(row[id_i].strip())))
            except: pass
        elif is_nse_fno and undl:
            fno.add(undl)  # add underlying stock name, not contract name
    return eq, fno

def ensure_symbols(tok=""):
    if len(SYMBOLS) >= 50: return True
    if load_symbols_disk(): return True
    if load_symbols_verified(): return True
    # Last resort — fetch CSV immediately (blocking)
    print(f"[sym] no symbols found — fetching CSV now...")
    if tok and load_symbols_csv(tok): return True
    print(f"[sym] WARNING: no symbols available — push fetch_ids.py to GitHub and run workflow")
    return False


def _upgrade_ids_background(tok):
    """Try CSV first. If that fails, fix wrong IDs via marketfeed scan."""
    if load_symbols_csv(tok):
        return  # CSV worked — all IDs now correct
    # CSV failed — scan for correct IDs of missing symbols
    fix_missing_ids(tok)


def fix_missing_ids(tok):
    """
    Scan all Dhan NSE_EQ IDs in focused ranges, collect tradingSymbol from each response.
    Builds a complete symbol→ID map and fixes any wrong IDs in SYMBOLS.
    Runs once in background after first screener run.
    Takes ~2-3 minutes but only runs when IDs are wrong.
    """
    global SYMBOLS, VERIFIED_IDS
    if not tok: return
    print("[fix] starting full ID scan...")
    headers = {"access-token": tok, "client-id": CREDS.get("client_id",""),
               "Content-Type": "application/json"}

    # Scan these ID ranges — covers all known Dhan NSE_EQ stock IDs
    # Total: ~25000 IDs in batches of 100 = 250 batches
    all_ids = list(range(1, 25001))
    target  = {s["symbol"] for s in SYMBOLS}
    found   = {}  # symbol → correct_id

    for i in range(0, len(all_ids), 100):
        if len(found) >= len(target): break
        batch = all_ids[i:i+100]
        for attempt in range(3):
            try:
                r = requests.post(f"{DHAN_BASE}/v2/marketfeed/ltp",
                                  json={"NSE_EQ": batch}, headers=headers, timeout=15)
                if r.status_code == 429:
                    time.sleep(6*(attempt+1)); continue
                if r.status_code == 200:
                    for sec_id, q in r.json().get("data",{}).get("NSE_EQ",{}).items():
                        sym = (q.get("tradingSymbol") or q.get("trading_symbol") or "").strip()
                        if sym in target:
                            found[sym] = str(int(float(sec_id)))
                    break
            except: time.sleep(1)
        time.sleep(0.8)
        if i % 2000 == 0:
            print(f"[fix] scanned {i+100}/25000 IDs, found {len(found)}/{len(target)}")

    print(f"[fix] scan complete: {len(found)}/{len(target)} symbols found")

    # Apply corrections for any symbols where ID changed
    corrections = {}
    current_map = {s["symbol"]: s["security_id"] for s in SYMBOLS}
    for sym, new_id in found.items():
        if current_map.get(sym) != new_id:
            corrections[sym] = new_id

    if corrections:
        VERIFIED_IDS.update(corrections)
        for s in SYMBOLS:
            if s["symbol"] in corrections:
                s["security_id"] = corrections[s["symbol"]]
        cache["symbol_source"] = "scanned"
        save_symbols()
        # Also update correct_ids.json so fixes persist across restarts
        try:
            cij = {s["symbol"]: s["security_id"] for s in SYMBOLS}
            with open("correct_ids.json", "w") as f:
                json.dump(cij, f, indent=2)
            print(f"[fix] saved corrections to correct_ids.json")
        except Exception as e:
            print(f"[fix] could not save correct_ids.json: {e}")
        print(f"[fix] corrected {len(corrections)} IDs: {list(corrections.items())[:5]}")
    else:
        print("[fix] no corrections needed")

# ── Quotes ─────────────────────────────────────────────────────────────────────
def get_all_quotes(tok):
    cid     = CREDS["client_id"]
    headers = {"access-token":tok,"client-id":cid,"Content-Type":"application/json"}
    id_map  = {s["security_id"]:s["symbol"] for s in SYMBOLS}
    quotes  = {}
    _logged = False
    _last_err = ""

    for i in range(0, len(SYMBOLS), 50):
        batch   = [int(s["security_id"]) for s in SYMBOLS[i:i+50]]
        payload = {"NSE_EQ": batch}
        for attempt in range(3):
            try:
                r = requests.post(f"{DHAN_BASE}/v2/marketfeed/quote",
                                  json=payload, headers=headers, timeout=15)
                print(f"  quote i={i} → {r.status_code}")
                if r.status_code == 200:
                    raw = r.json().get("data", {}).get("NSE_EQ", {})
                    if not _logged and raw:
                        first_key = next(iter(raw))
                        print(f"[debug] quote keys: {list(raw[first_key].keys())}")
                        print(f"[debug] sample: {raw[first_key]}")
                        _logged = True
                    for sid, q in raw.items():
                        sym = id_map.get(str(int(float(sid))))
                        if sym:
                            ohlc       = q.get("ohlc", {})
                            ltp        = float(q.get("last_price", 0))
                            # ohlc.close = previous day's close (settled price)
                            # This IS available from Dhan quote API — use it for change%
                            prev_close = round(float(ohlc.get("close", 0)), 2)
                            quotes[sym] = {
                                "ltp":        round(ltp, 2),
                                "prev_close": prev_close,
                                "volume":     int(q.get("volume", 0)),
                                "open":       round(float(ohlc.get("open", 0)), 2),
                                "high":       round(float(ohlc.get("high", 0)), 2),
                                "low":        round(float(ohlc.get("low",  0)), 2),
                            }
                    break
                elif r.status_code == 429:
                    time.sleep(5 * (attempt + 1))
                else:
                    # Log the actual error body so we can see WHY it failed
                    try:
                        _last_err = r.text[:300]
                    except:
                        _last_err = f"HTTP {r.status_code}"
                    print(f"  quote non-200: {r.status_code} | {_last_err}")
                    break
            except Exception as e:
                print(f"  quote err: {e}"); time.sleep(2)
        time.sleep(1.2)

    missing=[s["symbol"] for s in SYMBOLS if s["symbol"] not in quotes]
    print(f"[quotes] got={len(quotes)} missing={len(missing)} sample={missing[:5]}")
    if _last_err:
        print(f"[quotes] last API error: {_last_err}")
    cache["debug"]={"quotes_fetched":len(quotes),"missing_count":len(missing),
                    "missing_sample":missing[:10],"last_api_error":_last_err}

    # ── Fallback: if quote API returned nothing, try LTP endpoint ──────────────
    # Dhan's /v2/marketfeed/ltp works even after market hours and on weekends.
    if not quotes:
        print(f"[quotes] quote API returned 0 results — falling back to LTP endpoint...")
        quotes = _get_all_ltp(tok, id_map, headers)
        if quotes:
            cache["debug"]["fallback_used"] = "ltp"
            cache["debug"]["quotes_fetched"] = len(quotes)
            cache["debug"]["missing_count"]  = len([s for s in SYMBOLS if s["symbol"] not in quotes])

    return quotes


def _get_all_ltp(tok, id_map, headers):
    """
    Fallback quotes via /v2/marketfeed/ltp — available 24/7, returns last traded price.
    Does NOT include ohlc, so prev_close must come from historical data.
    """
    quotes = {}
    for i in range(0, len(SYMBOLS), 100):
        batch   = [int(s["security_id"]) for s in SYMBOLS[i:i+100]]
        payload = {"NSE_EQ": batch}
        for attempt in range(3):
            try:
                r = requests.post(f"{DHAN_BASE}/v2/marketfeed/ltp",
                                  json=payload, headers=headers, timeout=15)
                print(f"  ltp i={i} → {r.status_code}")
                if r.status_code == 200:
                    raw = r.json().get("data", {}).get("NSE_EQ", {})
                    for sid, q in raw.items():
                        sym = id_map.get(str(int(float(sid))))
                        if sym:
                            ltp = float(q.get("last_price", 0) or q.get("ltp", 0))
                            quotes[sym] = {
                                "ltp":        round(ltp, 2),
                                "prev_close": 0,  # not in LTP response — will come from historical
                                "volume":     int(q.get("volume", 0)),
                                "open": 0, "high": 0, "low": 0,
                            }
                    break
                elif r.status_code == 429:
                    time.sleep(5 * (attempt + 1))
                else:
                    print(f"  ltp non-200: {r.status_code} | {r.text[:200]}")
                    break
            except Exception as e:
                print(f"  ltp err: {e}"); time.sleep(2)
        time.sleep(0.8)
    print(f"[ltp] fallback got={len(quotes)}")
    return quotes

def get_historical(security_id, tok):
    today=ist_now()
    payload={"securityId":security_id,"exchangeSegment":"NSE_EQ","instrument":"EQUITY",
             "expiryCode":0,"fromDate":(today-timedelta(days=30)).strftime("%Y-%m-%d"),
             "toDate":today.strftime("%Y-%m-%d")}
    headers={"access-token":tok,"Content-Type":"application/json"}
    for attempt in range(3):
        try:
            r=requests.post(f"{DHAN_BASE}/v2/charts/historical",json=payload,headers=headers,timeout=10)
            if r.status_code==429: time.sleep(3*(attempt+1)); continue
            if r.status_code!=200: return None
            d=r.json(); return d if d.get("timestamp") else None
        except: time.sleep(1)
    return None

# ── Screener ───────────────────────────────────────────────────────────────────
def compute_metrics(q, hist, market_open, today_str):
    """
    change% formula:
      Market OPEN:   (ltp - closes[-1]) / closes[-1]      closes[-1] = yesterday settled
      Market CLOSED: (closes[-1] - closes[-2]) / closes[-2]  closes[-1] = today settled
    Fallback (no hist): use quote prev_close from Dhan API
    """
    ltp       = q["ltp"]
    today_vol = q["volume"]
    closes    = hist.get("close",  []) if hist else []
    volumes   = hist.get("volume", []) if hist else []

    # ── Change % ──────────────────────────────────────────────────────
    chg_pct    = 0.0
    prev_close = 0.0

    if len(closes) >= 2:
        if market_open:
            # Today's bar not yet settled — closes[-1] is yesterday's close
            prev_close = closes[-1]
            today_price = ltp
        else:
            # Market closed — closes[-1] is today's settled close
            # closes[-2] is yesterday's close
            today_price = closes[-1]
            prev_close  = closes[-2]
            ltp = today_price  # show today's close as LTP after hours
        if prev_close:
            chg_pct = round(((today_price - prev_close) / prev_close) * 100, 2)

    elif q.get("prev_close"):
        # Fallback: use Dhan's prev_close field
        prev_close = q["prev_close"]
        if prev_close:
            chg_pct = round(((ltp - prev_close) / prev_close) * 100, 2)

    # ── Momentum 5D ───────────────────────────────────────────────────
    momentum5d = 0.0
    if len(closes) >= 6:
        ref = closes[-1] if not market_open else ltp
        c5  = closes[-7] if not market_open else closes[-6]
        if c5: momentum5d = round(((ref - c5) / c5) * 100, 2)

    # ── Volume ratio ──────────────────────────────────────────────────
    vol_ratio = 0.0; avg_vol7d = 0
    if len(volumes) >= 8:
        if market_open:
            avg_vol7d = int(sum(volumes[-8:-1]) / 7)
            vol_ratio = round(today_vol / avg_vol7d, 2) if avg_vol7d else 0
        else:
            # Market closed — volumes[-1] is today's final volume
            avg_vol7d = int(sum(volumes[-8:-1]) / 7)
            vol_ratio = round(volumes[-1] / avg_vol7d, 2) if avg_vol7d else 0
    elif today_vol > 0:
        vol_ratio = 1.0

    return chg_pct, round(prev_close, 2), momentum5d, vol_ratio, int(avg_vol7d)


def run_screener(tok):
    global cache
    ensure_symbols(tok)
    if not SYMBOLS:
        cache.update({"status": "error", "errors": ["No symbols"]}); return

    market_open = is_market_open()
    today_str   = ist_now().strftime("%Y-%m-%d")

    # ── Market CLOSED ──────────────────────────────────────────────────────────
    # Use quote API: ltp = today's final close, ohlc.close = yesterday's close
    # change% = (ltp - prev_close) / prev_close * 100  ← simple and correct
    if not market_open:
        if cache.get("data") and cache.get("updated_at"):
            print(f"[screener] market closed — keeping settled data ({len(cache['data'])} results)")
            cache.update({"status": "ok", "market_open": False, "progress": 100, "errors": []})
            return

        print(f"[screener] market closed — fetching settled prices via quote API")
        total = len(SYMBOLS)
        cache.update({"status": "fetching", "progress": 5, "total": total, "market_open": False})

        quotes = get_all_quotes(tok)
        # On weekends / after hours the quote API may return empty — don't hard-fail.
        # Historical data alone is enough to compute change% and volume ratios.
        if not quotes:
            print(f"[screener] quote API returned 0 — will rely entirely on historical data")
            cache.update({"status": "fetching", "errors": ["quote API empty — using historical only"]})
        cache["progress"] = 20

        # Historical provides prev_close, momentum, and vol ratio.
        # Fetch for ALL symbols — even if quotes is empty (weekend/after-hours).
        print(f"[screener] fetching historical for prev_close + momentum...")
        hist_data = {}
        syms = SYMBOLS  # fetch historical for everyone, not just quote-matched
        for i, sym in enumerate(syms):
            hist = get_historical(sym["security_id"], tok)
            if hist:
                hist_data[sym["symbol"]] = hist
            cache["progress"] = 20 + round((i + 1) / len(syms) * 70)
            time.sleep(0.4)
            if (i + 1) % 30 == 0:
                time.sleep(2)

        print(f"[screener] historical done: {len(hist_data)} fetched")
        cache["progress"] = 92

        results, skipped = [], []
        for sym in SYMBOLS:
            try:
                q    = quotes.get(sym["symbol"])
                hist = hist_data.get(sym["symbol"])

                # ── Determine LTP ──────────────────────────────────────────────
                if q:
                    ltp = q["ltp"]
                elif hist and hist.get("close"):
                    # No quote data (weekend/after-hours) — use last historical close
                    ltp = hist["close"][-1]
                else:
                    skipped.append(f"{sym['symbol']}:no_ltp"); continue

                if not ltp:
                    skipped.append(f"{sym['symbol']}:ltp=0"); continue

                # ── Determine prev_close ───────────────────────────────────────
                if q and q.get("prev_close"):
                    # ohlc.close from quote API = previous day's settled price ✓
                    prev_close = q["prev_close"]
                elif hist and hist.get("close") and len(hist["close"]) >= 2:
                    closes = hist["close"]
                    # If last hist close ≈ ltp, today is included → use [-2]
                    if abs(closes[-1] - ltp) / max(ltp, 0.01) < 0.001:
                        prev_close = closes[-2]
                    else:
                        prev_close = closes[-1]
                # ── Compute change%, momentum, vol ratio from historical ────────
                chg_pct = round((ltp - prev_close) / prev_close * 100, 2) if prev_close else 0.0

                mom5d = 0.0; vol_ratio = 0.0; avg_vol7d = 0
                if hist:
                    closes  = hist.get("close",  [])
                    volumes = hist.get("volume", [])
                    # Build ref_closes: includes today
                    if closes and abs(closes[-1] - ltp) / max(ltp, 0.01) < 0.001:
                        ref_closes = closes
                    else:
                        ref_closes = closes + [ltp]

                    if len(ref_closes) >= 6:
                        c5 = ref_closes[-6]
                        if c5: mom5d = round((ltp - c5) / c5 * 100, 2)

                    today_vol = (q["volume"] if q else 0)
                    if len(volumes) >= 8:
                        avg_vol7d = int(sum(volumes[-8:-1]) / 7)
                        vol_ratio = round(today_vol / avg_vol7d, 2) if avg_vol7d else 0.0

                print(f"[close] {sym['symbol']} ltp={ltp} prev={prev_close} chg={chg_pct}%") if sym["symbol"] in ("ANGELONE","SAIL","MANAPPURAM","RELIANCE") else None

                results.append({
                    "symbol":      sym["symbol"], "exchange": "NSE",
                    "ltp":         ltp,           "prev_close": round(prev_close, 2),
                    "change":      chg_pct,       "momentum5d": mom5d,
                    "volumeRatio": vol_ratio,     "todayVol":   q["volume"],
                    "avgVol7d":    avg_vol7d,
                })
            except Exception as e:
                skipped.append(f"{sym['symbol']}:{e}")
                print(f"[screener] {sym['symbol']} error: {e}")

        results.sort(key=lambda x: x["volumeRatio"], reverse=True)
        cache.update({"data": results, "updated_at": ist_now().strftime("%H:%M:%S IST"),
            "status": "ok", "count": len(results), "errors": [], "skipped": skipped[:20],
            "progress": 100, "market_open": False})
        print(f"[screener] closed-market done — {len(results)} ok | {len(skipped)} skipped")
        return

    # ── Market OPEN ────────────────────────────────────────────────────────────
    # Fast: quotes for live ltp + change%, historical in background for momentum/vol
    total = len(SYMBOLS)
    cache.update({"status": "fetching", "progress": 5, "total": total, "market_open": True})
    print(f"[screener] market open — {total} symbols | {ist_now().strftime('%H:%M:%S IST')}")

    quotes = get_all_quotes(tok)
    if not quotes:
        cache.update({"status": "error", "errors": ["0 quotes returned"]}); return
    cache["progress"] = 60

    results, skipped = [], []
    for sym in SYMBOLS:
        try:
            q = quotes.get(sym["symbol"])
            if not q: skipped.append(f"{sym['symbol']}:no_quote"); continue
            pc  = q.get("prev_close", 0)
            ltp = q["ltp"]
            chg = round((ltp - pc) / pc * 100, 2) if pc else 0.0
            # Reuse momentum/vol from previous run if available
            prev = next((r for r in cache.get("data", []) if r["symbol"] == sym["symbol"]), {})
            results.append({
                "symbol":      sym["symbol"], "exchange": "NSE",
                "ltp":         ltp,           "prev_close": pc,
                "change":      chg,           "momentum5d": prev.get("momentum5d", 0.0),
                "volumeRatio": prev.get("volumeRatio", 0.0), "todayVol": q["volume"],
                "avgVol7d":    prev.get("avgVol7d", 0),
            })
        except Exception as e:
            skipped.append(f"{sym['symbol']}:{e}")

    results.sort(key=lambda x: x["volumeRatio"], reverse=True)
    cache.update({"data": results, "updated_at": ist_now().strftime("%H:%M:%S IST"),
        "status": "ok", "count": len(results), "errors": [], "skipped": skipped[:20],
        "progress": 100, "market_open": True})
    print(f"[screener] open-market done — {len(results)} ok | {len(skipped)} skipped")

    # Enrich momentum + vol ratio in background
    threading.Thread(target=_enrich_historical,
                     args=(tok, quotes, True, today_str), daemon=True).start()

    # Fix missing IDs if needed
    missing_count = cache.get("debug", {}).get("missing_count", 0)
    if missing_count > 10 and cache["symbol_source"] in ("verified", "disk", "correct_ids_json"):
        threading.Thread(target=fix_missing_ids, args=(tok,), daemon=True).start()


def _enrich_historical(tok, quotes, market_open, today_str):
    """Background: fetch historical data and update cache with momentum + vol ratio."""
    global cache
    print(f"[hist] starting background historical fetch for {len(quotes)} symbols...")
    syms = [s for s in SYMBOLS if s["symbol"] in quotes]
    hist_data = {}

    for i, sym in enumerate(syms):
        hist = get_historical(sym["security_id"], tok)
        if hist:
            hist_data[sym["symbol"]] = hist
        time.sleep(0.4)
        if (i + 1) % 30 == 0:
            time.sleep(2)

    print(f"[hist] got {len(hist_data)} historical records — updating cache...")

    # Build result map from current cache
    result_map = {r["symbol"]: dict(r) for r in cache.get("data", [])}

    for sym_name, hist in hist_data.items():
        if sym_name not in result_map: continue
        q = quotes.get(sym_name)
        if not q: continue
        chg, pc, mom5d, vol_ratio, avg_vol7d = compute_metrics(q, hist, market_open, today_str)
        result_map[sym_name].update({
            "prev_close":  pc,
            "change":      chg,
            "momentum5d":  mom5d,
            "volumeRatio": vol_ratio,
            "avgVol7d":    avg_vol7d,
        })

    enriched = sorted(result_map.values(), key=lambda x: x["volumeRatio"], reverse=True)
    cache.update({"data": enriched, "count": len(enriched),
                  "updated_at": ist_now().strftime("%H:%M:%S IST")})
    print(f"[hist] cache enriched with historical data ✓")

def trigger_screener(cid="",tok=""):
    cid=cid or CREDS["client_id"]; tok=tok or CREDS["access_token"]
    if not cid or not tok: cache["status"]="no_credentials"; return
    CREDS["client_id"]=cid; CREDS["access_token"]=tok
    if _lock.locked(): return
    threading.Thread(target=lambda:_run_locked(tok),daemon=True).start()

def _run_locked(tok):
    with _lock: run_screener(tok)

# ── Scheduler ──────────────────────────────────────────────────────────────────
def scheduled_job():
    tok=CREDS.get("access_token",""); cid=CREDS.get("client_id","")
    if not tok or not cid: return
    now=ist_now()
    if now.hour==8 and now.minute<10:
        threading.Thread(target=load_symbols_csv,args=(tok,),daemon=True).start()
    trigger_screener(cid,tok)

def keep_alive():
    if SELF_URL:
        try: requests.get(f"{SELF_URL}/api/health",timeout=10)
        except: pass

scheduler=BackgroundScheduler()
scheduler.add_job(scheduled_job,"interval",minutes=5,id="screener")
scheduler.add_job(keep_alive,"interval",minutes=10,id="keepalive")
scheduler.start()

# ── Startup ────────────────────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app):
    def _boot():
        tok=CREDS.get("access_token",""); cid=CREDS.get("client_id","")
        print(f"[boot] cid={'SET' if cid else 'MISSING'} tok={'SET' if tok else 'MISSING'}")
        ensure_symbols(tok)
        print(f"[boot] symbols={len(SYMBOLS)} source={cache['symbol_source']}")
        if cid and tok: trigger_screener(cid,tok)
        else: print("[boot] no creds — set DHAN_CLIENT_ID + DHAN_ACCESS_TOKEN on Render")
    threading.Thread(target=_boot,daemon=True).start()
    yield

app = FastAPI(title="TradeAs API", version="3.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ── Routes ─────────────────────────────────────────────────────────────────────
@app.get("/")
def root(): return {"status":"ok","time_ist":ist_now().strftime("%H:%M:%S"),"market_open":is_market_open()}

@app.get("/api/health")
def health():
    return {"status":"ok","cache_status":cache["status"],"last_refresh":cache["updated_at"],
            "symbol_count":len(SYMBOLS),"symbol_source":cache["symbol_source"],
            "result_count":cache["count"],"error_count":len(cache.get("errors",[])),
            "skipped_count":len(cache.get("skipped",[])),"skipped_sample":cache.get("skipped",[])[:5],
            "progress_pct":cache.get("progress",0),"market_open":is_market_open(),
            "time_ist":ist_now().strftime("%H:%M:%S"),"day":ist_now().strftime("%A"),
            "debug":cache.get("debug",{})}

@app.get("/api/screener")
def get_screener(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    cid=x_client_id or CREDS.get("client_id",""); tok=x_access_token or CREDS.get("access_token","")
    if cid: CREDS["client_id"]=cid
    if tok: CREDS["access_token"]=tok
    if cid and tok and cache.get("status") in ("idle","no_credentials","error"):
        trigger_screener(cid,tok)
    return cache

@app.get("/api/boot")
@app.post("/api/boot")
def boot(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    cid=x_client_id or CREDS.get("client_id",""); tok=x_access_token or CREDS.get("access_token","")
    if cid: CREDS["client_id"]=cid
    if tok: CREDS["access_token"]=tok
    ensure_symbols(tok)
    if cid and tok: trigger_screener(cid,tok)
    return {"symbols":len(SYMBOLS),"source":cache["symbol_source"],
            "screener":"triggered" if (cid and tok) else "no_creds",
            "tip":"Poll /api/health for progress"}

@app.get("/api/debug")
def debug(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    cid=x_client_id or CREDS.get("client_id",""); tok=x_access_token or CREDS.get("access_token","")
    return {"symbol_count":len(SYMBOLS),"symbol_source":cache["symbol_source"],
            "screener_status":cache["status"],"has_client_id":bool(cid),"has_token":bool(tok),
            "env_client_id":bool(os.getenv("DHAN_CLIENT_ID")),"env_token":bool(os.getenv("DHAN_ACCESS_TOKEN")),
            "lock_held":_lock.locked(),"sample_symbols":SYMBOLS[:3],"last_debug":cache.get("debug",{})}

@app.get("/api/logs")
def get_logs(n:int=100):
    """Returns last N log lines — useful for debugging without opening Render dashboard."""
    with _log_lock:
        lines = _log_buffer[-n:]
    return {"count":len(lines),"logs":lines}

@app.post("/api/symbols/refresh")
def refresh_symbols(x_access_token:str=Header(None)):
    tok=x_access_token or CREDS.get("access_token","")
    ok=load_symbols_csv(tok)
    if not ok: load_symbols_verified()
    return {"ok":ok,"count":len(SYMBOLS),"source":cache["symbol_source"]}

@app.get("/api/symbols")
def list_symbols():
    return {"count":len(SYMBOLS),"source":cache["symbol_source"],"symbols":SYMBOLS}

@app.get("/api/screener/top")
def top(limit:int=20): return {"data":cache["data"][:limit]}

@app.get("/api/screener/gainers")
def gainers(): return {"data":sorted([x for x in cache["data"] if x["change"]>0],key=lambda x:x["change"],reverse=True)[:15]}

@app.get("/api/screener/losers")
def losers(): return {"data":sorted([x for x in cache["data"] if x["change"]<0],key=lambda x:x["change"])[:15]}

@app.get("/api/screener/volume-spike")
def vol_spike(min_ratio:float=2.0): return {"data":[x for x in cache["data"] if x["volumeRatio"]>=min_ratio]}

@app.get("/api/screener/momentum")
def momentum(min_pct:float=3.0): return {"data":[x for x in cache["data"] if x["momentum5d"]>=min_pct]}

@app.get("/api/ping-dhan")
def ping_dhan(x_access_token:str=Header(None)):
    tok=x_access_token or CREDS.get("access_token","")
    if not tok: return {"connected":False,"error":"No token"}
    try:
        r=requests.get(f"{DHAN_BASE}/v2/profile",headers={"access-token":tok},timeout=5)
        return {"connected":r.status_code==200,"status":r.status_code}
    except Exception as e: return {"connected":False,"error":str(e)}

@app.get("/api/historical")
def proxy_historical(security_id:str=Query(...),from_date:str=Query(...),to_date:str=Query(...),x_access_token:str=Header(None)):
    tok=x_access_token or CREDS.get("access_token","")
    if not tok: return {"status":"no_credentials"}
    headers={"access-token":tok,"Content-Type":"application/json"}
    payload={"securityId":security_id,"exchangeSegment":"NSE_EQ","instrument":"EQUITY","expiryCode":0,"fromDate":from_date,"toDate":to_date}
    try:
        r=requests.post(f"{DHAN_BASE}/v2/charts/historical",json=payload,headers=headers,timeout=15)
        return {"status":"ok","data":r.json()} if r.status_code==200 else {"status":"error","code":r.status_code}
    except Exception as e: return {"status":"error","error":str(e)}

@app.get("/api/ltp")
def get_ltp(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    cid=x_client_id or CREDS.get("client_id",""); tok=x_access_token or CREDS.get("access_token","")
    if not cid or not tok: return {"status":"no_credentials","quotes":{}}
    ensure_symbols(tok)
    quotes=get_all_quotes(tok)
    return {"status":"ok","count":len(quotes),"quotes":quotes,
            "updated_at":ist_now().strftime("%H:%M:%S IST"),"market_open":is_market_open()}

@app.get("/api/ltp/live")
def get_ltp_live(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    """Fast LTP-only fetch from Dhan marketfeed/ltp — used for 10s price refresh.
    Much faster than /api/ltp as it only fetches last_price, no OHLC/volume."""
    cid=x_client_id or CREDS.get("client_id",""); tok=x_access_token or CREDS.get("access_token","")
    if not cid or not tok: return {"status":"no_credentials","quotes":{}}
    ensure_symbols(tok)
    headers={"access-token":tok,"client-id":cid,"Content-Type":"application/json"}
    id_map={s["security_id"]:s["symbol"] for s in SYMBOLS}
    # Also build prev_close from existing cache for change% computation
    prev_map={r["symbol"]:r["prev_close"] for r in cache.get("data",[]) if r.get("prev_close")}
    quotes={}
    for i in range(0,len(SYMBOLS),100):
        batch=[int(s["security_id"]) for s in SYMBOLS[i:i+100]]
        for attempt in range(2):
            try:
                r=requests.post(f"{DHAN_BASE}/v2/marketfeed/ltp",
                                json={"NSE_EQ":batch},headers=headers,timeout=10)
                if r.status_code==200:
                    for sid,q in r.json().get("data",{}).get("NSE_EQ",{}).items():
                        sym=id_map.get(str(int(float(sid))))
                        if sym:
                            ltp=round(float(q.get("last_price",0)),2)
                            pc=prev_map.get(sym,0)
                            quotes[sym]={"ltp":ltp,"prev_close":pc}
                    break
                elif r.status_code==429:
                    time.sleep(3*(attempt+1))
            except Exception as e:
                time.sleep(1)
        time.sleep(0.3)
    return {"status":"ok","count":len(quotes),"quotes":quotes,
            "updated_at":ist_now().strftime("%H:%M:%S IST"),"market_open":is_market_open()}

# ── Option Chain ───────────────────────────────────────────────────────────────
_opt_cache = {"data": [], "updated_at": None, "status": "idle", "count": 0, "market_open": False}
_opt_lock  = threading.Lock()

def _get_nearest_expiry(tok, cid, scrip_id):
    headers = {"access-token": tok, "client-id": cid, "Content-Type": "application/json"}
    try:
        r = requests.post(f"{DHAN_BASE}/v2/optionchain/expirylist",
                          json={"UnderlyingScrip": int(scrip_id), "UnderlyingSeg": "NSE_EQ"},
                          headers=headers, timeout=10)
        if r.status_code == 200:
            dates = r.json().get("data", [])
            return dates[0] if dates else None
        print(f"[opt] expirylist {r.status_code}: {r.text[:120]}")
    except Exception as e:
        print(f"[opt] expirylist error: {e}")
    return None

def _analyze_options(tok, cid):
    global _opt_cache
    if not SYMBOLS or not tok: return
    _opt_cache["status"] = "fetching"
    headers = {"access-token": tok, "client-id": cid, "Content-Type": "application/json"}
    results = []

    # Wait for screener data
    wait = 0
    while not cache.get("data") and wait < 120:
        print(f"[opt] waiting for screener data... ({wait}s)")
        time.sleep(5); wait += 5
    if not cache.get("data"):
        print(f"[opt] screener data not available — aborting")
        _opt_cache["status"] = "idle"; return

    spot_map = {x["symbol"]: x["ltp"] for x in cache.get("data", [])}
    print(f"[opt] starting analysis, {len(spot_map)} spot prices available")

    # Get nearest expiry from first available symbol
    nearest_expiry = None
    for sym_info in SYMBOLS[:10]:
        if not spot_map.get(sym_info["symbol"]): continue
        exp = _get_nearest_expiry(tok, cid, sym_info["security_id"])
        time.sleep(3)  # rate limit: 1 req per 3s
        if exp:
            nearest_expiry = exp
            print(f"[opt] nearest expiry: {nearest_expiry} (from {sym_info['symbol']})")
            break

    if not nearest_expiry:
        print(f"[opt] could not get expiry — aborting")
        _opt_cache["status"] = "error"; return

    for sym_info in SYMBOLS:
        sym   = sym_info["symbol"]
        eq_id = sym_info["security_id"]
        spot  = spot_map.get(sym, 0)
        if not spot: continue

        try:
            time.sleep(3)  # rate limit: 1 request per 3 seconds
            r = requests.post(
                f"{DHAN_BASE}/v2/optionchain",
                json={"UnderlyingScrip": int(eq_id), "UnderlyingSeg": "NSE_EQ", "Expiry": nearest_expiry},
                headers=headers, timeout=15
            )
            if r.status_code == 429:
                print(f"[opt] {sym} 429 — sleeping 6s"); time.sleep(6); continue
            if r.status_code != 200:
                print(f"[opt] {sym} {r.status_code}: {r.text[:120]}"); continue

            resp = r.json()
            if resp.get("status") != "success":
                print(f"[opt] {sym} not success: {str(resp)[:120]}"); continue

            oc = resp.get("data", {}).get("oc", {})
            if not oc: continue
            if not results:
                print(f"[opt] first success: {sym}, {len(oc)} strikes")

            total_ce_oi = total_pe_oi = total_ce_vol = total_pe_vol = 0
            atm_ce_oi = atm_pe_oi = atm_ce_vol = atm_pe_vol = 0
            atm_strike = 0; min_diff = float("inf")

            for strike_str, sd in oc.items():
                sp     = float(strike_str)
                ce     = sd.get("ce", {})
                pe     = sd.get("pe", {})
                ce_oi  = int(ce.get("oi", 0))
                pe_oi  = int(pe.get("oi", 0))
                ce_vol = int(ce.get("volume", 0))
                pe_vol = int(pe.get("volume", 0))
                total_ce_oi += ce_oi;  total_pe_oi  += pe_oi
                total_ce_vol += ce_vol; total_pe_vol += pe_vol
                diff = abs(sp - spot)
                if diff < min_diff:
                    min_diff = diff; atm_strike = sp
                    atm_ce_oi = ce_oi; atm_pe_oi = pe_oi
                    atm_ce_vol = ce_vol; atm_pe_vol = pe_vol

            if total_ce_oi + total_pe_oi == 0: continue
            pcr          = round(total_pe_oi / total_ce_oi, 2) if total_ce_oi else 0
            ce_vol_ratio = round(atm_ce_vol / (atm_ce_oi / 100), 2) if atm_ce_oi else 0
            pe_vol_ratio = round(atm_pe_vol / (atm_pe_oi / 100), 2) if atm_pe_oi else 0

            bull = 0
            if pcr < 0.7:                         bull += 2
            if ce_vol_ratio > 5:                   bull += 2
            if atm_pe_oi > atm_ce_oi * 1.5:       bull += 1
            if total_ce_vol > total_pe_vol * 1.5:  bull += 1

            bear = 0
            if pcr > 1.3:                          bear += 2
            if pe_vol_ratio > 5:                   bear += 2
            if atm_ce_oi > atm_pe_oi * 1.5:       bear += 1
            if total_pe_vol > total_ce_vol * 1.5:  bear += 1

            signal = "neutral"; strength = 0
            if bull >= 3 and bull > bear:   signal = "bullish"; strength = bull
            elif bear >= 3 and bear > bull: signal = "bearish"; strength = bear

            vol_spike = ""
            if   ce_vol_ratio > 8 and pe_vol_ratio > 8: vol_spike = "BOTH"
            elif ce_vol_ratio > 8:                       vol_spike = "CE"
            elif pe_vol_ratio > 8:                       vol_spike = "PE"

            results.append({
                "symbol": sym, "spot": spot, "atm_strike": atm_strike,
                "expiry": nearest_expiry,
                "pcr": pcr, "signal": signal, "signal_strength": strength,
                "ce_oi": total_ce_oi, "pe_oi": total_pe_oi,
                "ce_vol": total_ce_vol, "pe_vol": total_pe_vol,
                "atm_ce_oi": atm_ce_oi, "atm_pe_oi": atm_pe_oi,
                "atm_ce_vol": atm_ce_vol, "atm_pe_vol": atm_pe_vol,
                "ce_vol_ratio": ce_vol_ratio, "pe_vol_ratio": pe_vol_ratio,
                "vol_spike": vol_spike,
            })
        except Exception as e:
            print(f"[opt] {sym} exception: {e}"); continue

    results.sort(key=lambda x: x["signal_strength"], reverse=True)
    _opt_cache.update({"data": results, "updated_at": ist_now().strftime("%H:%M:%S IST"),
                       "status": "ok", "count": len(results), "market_open": is_market_open()})
    print(f"[opt] done — {len(results)} symbols analysed")

def _run_opt_locked(tok, cid):
    with _opt_lock: _analyze_options(tok, cid)

def _opt_stale():
    """Returns True only if data is older than 5 minutes."""
    last = _opt_cache.get("updated_at")
    if not last: return True
    try:
        t = datetime.strptime(last, "%H:%M:%S IST").replace(
            year=ist_now().year, month=ist_now().month, day=ist_now().day, tzinfo=IST)
        return (ist_now() - t).seconds > 300  # 5 min stale threshold
    except: return True

@app.get("/api/options")
def get_options(x_client_id:str=Header(None), x_access_token:str=Header(None),
                refresh:bool=Query(False)):
    cid=x_client_id or CREDS.get("client_id",""); tok=x_access_token or CREDS.get("access_token","")
    if not cid or not tok: return {"status":"no_credentials","data":[]}
    CREDS["client_id"]=cid; CREDS["access_token"]=tok
    # Only trigger if: forced refresh OR stale AND not already running
    should_run = (refresh or (_opt_stale() and not _opt_cache["data"])) and not _opt_lock.locked()
    if should_run:
        print(f"[opt] triggering analysis (refresh={refresh} stale={_opt_stale()} locked={_opt_lock.locked()})")
        threading.Thread(target=_run_opt_locked, args=(tok,cid), daemon=True).start()
    return _opt_cache

@app.get("/api/options/bullish")
def opt_bullish(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    return {"data":[x for x in _opt_cache["data"] if x["signal"]=="bullish"]}

@app.get("/api/options/bearish")
def opt_bearish(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    return {"data":[x for x in _opt_cache["data"] if x["signal"]=="bearish"]}

@app.get("/api/options/volspike")
def opt_volspike(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    return {"data":[x for x in _opt_cache["data"] if x["vol_spike"]]}

# ── Breakout Scanner (9:45 Opening Range) ─────────────────────────────────────
# Strategy: capture the HIGH and LOW of every FNO stock from 9:15–9:45.
# After 9:45, any candle that closes ABOVE the range high = BULL breakout.
#           any candle that closes BELOW the range low  = BEAR breakdown.
# Shows: breakout time, % move from 9:45 price, today's volume vs 7-day avg.
# No momentum filter — just price + volume confirmation.
_bk_cache = {"data": [], "updated_at": None, "status": "idle", "market_open": False}
_bk_lock  = threading.Lock()

RANGE_END = "09:45"   # Opening range: 9:15 to 9:45

def _last_trading_day() -> str:
    """Return the most recent trading day (Mon–Fri) in YYYY-MM-DD format.
    If today is a weekday and market has opened (past 9:15), use today.
    Otherwise step back to the last weekday."""
    d = ist_now()
    # If market is open right now — use today
    if is_market_open():
        return d.strftime("%Y-%m-%d")
    # If today is a weekday AND we are past 9:15 (market has already traded today)
    if d.weekday() < 5 and (d.hour > 9 or (d.hour == 9 and d.minute >= 15)):
        return d.strftime("%Y-%m-%d")
    # Otherwise go back to the last weekday
    d -= timedelta(days=1)
    while d.weekday() >= 5:   # skip Sat(5) and Sun(6)
        d -= timedelta(days=1)
    return d.strftime("%Y-%m-%d")


def _compute_breakout(tok):
    global _bk_cache
    if not SYMBOLS or not tok: return
    _bk_cache["status"] = "fetching"
    cid     = CREDS.get("client_id", "")
    headers = {"access-token": tok, "client-id": cid, "Content-Type": "application/json"}
    now     = ist_now()
    today   = _last_trading_day()
    # Dhan intraday accepts "YYYY-MM-DD HH:MM:SS" format
    from_dt = f"{today} 09:15:00"
    to_dt   = f"{today} 15:30:00"
    print(f"[bk] trading date={today} now={now.strftime('%Y-%m-%d %H:%M %a')}")

    # Wait for screener data
    wait = 0
    while not cache.get("data") and wait < 120:
        print(f"[bk] waiting for screener data... ({wait}s)")
        time.sleep(5); wait += 5
    if not cache.get("data"):
        print(f"[bk] no screener data — aborting")
        _bk_cache["status"] = "idle"; return

    vol_map = {x["symbol"]: (x.get("todayVol", 0), x.get("avgVol7d", 0))
               for x in cache.get("data", [])}

    print(f"[bk] scanning {len(SYMBOLS)} symbols, RANGE_END={RANGE_END}")
    results = []
    ok_count = 0
    empty_count = 0
    no_range_count = 0
    no_break_count = 0

    for sym_info in SYMBOLS:
        sym = sym_info["symbol"]
        try:
            r = requests.post(
                f"{DHAN_BASE}/v2/charts/intraday",
                json={"securityId": str(sym_info["security_id"]),
                      "exchangeSegment": "NSE_EQ", "instrument": "EQUITY",
                      "interval": "1", "oi": False,
                      "fromDate": from_dt, "toDate": to_dt},
                headers=headers, timeout=10)
            if r.status_code == 429:
                print(f"[bk] 429 on {sym} — sleeping 5s"); time.sleep(5); continue
            if r.status_code != 200:
                continue

            d          = r.json()
            timestamps = d.get("timestamp", [])
            highs      = d.get("high",   [])
            lows       = d.get("low",    [])
            closes     = d.get("close",  [])
            volumes    = d.get("volume", [])

            if not timestamps:
                empty_count += 1
                if empty_count <= 3:
                    print(f"[bk] {sym} empty response — keys={list(d.keys())}")
                continue

            # ── Step 1: Build 9:15–9:45 opening range ─────────────────────
            # Include candles from 09:15 up to and including 09:45
            range_highs  = []
            range_lows   = []
            range_ref    = 0.0   # close of last candle in range (9:45 close)

            for i, ts in enumerate(timestamps):
                t = datetime.fromtimestamp(ts, IST).strftime("%H:%M")
                if "09:15" <= t <= RANGE_END:
                    range_highs.append(highs[i])
                    range_lows.append(lows[i])
                    range_ref = closes[i]   # last one = 9:45 close

            if len(range_highs) < 2:
                no_range_count += 1
                if no_range_count <= 3:
                    # Debug: show what times we actually got
                    all_times = [datetime.fromtimestamp(ts, IST).strftime("%H:%M")
                                 for ts in timestamps[:10]]
                    print(f"[bk] {sym} not enough range candles ({len(range_highs)}) — first times: {all_times}")
                continue

            range_high = round(max(range_highs), 2)
            range_low  = round(min(range_lows),  2)
            range_ref  = round(range_ref, 2)
            if range_ref <= 0: continue

            # ── Step 2: Find first candle AFTER range that breaks high or low ──
            # A breakout = any candle whose HIGH > range_high (bull)
            #           or any candle whose LOW  < range_low  (bear)
            # Using high/low (not close) catches the break the moment it happens
            signal_time  = None
            signal_price = 0.0
            direction    = None
            move_pct     = 0.0
            ltp          = 0.0   # last close seen (= final close of the day)

            for i, ts in enumerate(timestamps):
                t = datetime.fromtimestamp(ts, IST).strftime("%H:%M")
                if t <= RANGE_END: continue        # skip opening range candles
                ltp = closes[i]                    # track current price
                if direction is None:
                    if highs[i] > range_high:      # bull: high exceeds range high
                        direction    = "bull"
                        signal_time  = t
                        signal_price = round(highs[i], 2)
                        move_pct     = round((highs[i] - range_ref) / range_ref * 100, 2)
                    elif lows[i] < range_low:       # bear: low breaks range low
                        direction    = "bear"
                        signal_time  = t
                        signal_price = round(lows[i], 2)
                        move_pct     = round((lows[i] - range_ref) / range_ref * 100, 2)

            if not direction:
                no_break_count += 1; continue
            if ltp == 0: continue

            current_pct = round((ltp - range_ref) / range_ref * 100, 2)
            today_vol, avg_vol = vol_map.get(sym, (0, 0))
            vol_ratio    = round(today_vol / avg_vol, 2) if avg_vol else 0.0
            vol_confirmed = vol_ratio >= 1.5
            ok_count += 1

            results.append({
                "symbol":        sym,
                "ltp":           round(ltp, 2),
                "rangeHigh":     range_high,
                "rangeLow":      range_low,
                "rangeRef":      range_ref,
                "direction":     direction,
                "signal_time":   signal_time,
                "signal_price":  signal_price,
                "move_pct":      move_pct,
                "current_pct":   current_pct,
                "vol_ratio":     vol_ratio,
                "vol_confirmed": vol_confirmed,
                "today_vol":     today_vol,
            })
            time.sleep(0.25)

        except Exception as e:
            print(f"[bk] {sym} error: {e}"); continue

    print(f"[bk] done: ok={ok_count} empty={empty_count} no_range={no_range_count} no_break={no_break_count}")

    results.sort(key=lambda x: abs(x["current_pct"]), reverse=True)
    _bk_cache.update({
        "data":         results,
        "updated_at":   ist_now().strftime("%H:%M:%S IST"),
        "status":       "ok",
        "count":        len(results),
        "bulls":        sum(1 for r in results if r["direction"] == "bull"),
        "bears":        sum(1 for r in results if r["direction"] == "bear"),
        "vol_confirmed":sum(1 for r in results if r["vol_confirmed"]),
        "market_open":  is_market_open(),
        "range_end":    RANGE_END,
        "trading_date": today,   # track which day this data is for
    })
    print(f"[bk] done — {len(results)} breakouts ({_bk_cache['bulls']} bull, {_bk_cache['bears']} bear)")

def _run_bk_locked(tok):
    with _bk_lock: _compute_breakout(tok)

def _bk_stale():
    # Stale if: no data, or data is from a different trading day, or older than 5 min
    if not _bk_cache.get("data") and not _bk_cache.get("updated_at"):
        return True
    # Check if the trading date used for current data matches what we'd use now
    cached_date = _bk_cache.get("trading_date", "")
    if cached_date and cached_date != _last_trading_day():
        return True   # new trading day — must re-scan
    last = _bk_cache.get("updated_at")
    if not last: return True
    try:
        t = datetime.strptime(last, "%H:%M:%S IST").replace(
            year=ist_now().year, month=ist_now().month, day=ist_now().day, tzinfo=IST)
        # Live: stale after 5 min. Closed: stale after 1 hour (data won't change)
        threshold = 300 if is_market_open() else 3600
        return (ist_now() - t).seconds > threshold
    except: return True

@app.get("/api/breakout")
def get_breakout(x_client_id:str=Header(None), x_access_token:str=Header(None),
                 refresh:bool=Query(False)):
    cid = x_client_id or CREDS.get("client_id","")
    tok = x_access_token or CREDS.get("access_token","")
    if not cid or not tok: return {"status":"no_credentials","data":[]}
    CREDS["client_id"]=cid; CREDS["access_token"]=tok

    now         = ist_now()
    market_open = is_market_open()

    # Range ends at 9:45 — only gate is during the opening range itself
    range_complete = now.replace(hour=9, minute=45, second=0, microsecond=0)
    if market_open and now < range_complete:
        mins_left = int((range_complete - now).seconds / 60)
        return {"status":"waiting", "data":[], "market_open":True,
                "message":f"Building opening range (9:15–9:45) — {mins_left} min left",
                "range_end": RANGE_END}

    # Run when: forced refresh, data is stale, or no data yet
    # Works both market open (live) and closed (shows today's final breakouts)
    should_run = (refresh or _bk_stale() or not _bk_cache.get("data")) and not _bk_lock.locked()
    if should_run:
        threading.Thread(target=_run_bk_locked, args=(tok,), daemon=True).start()

    return _bk_cache

# ══════════════════════════════════════════════════════════════════════════════
# POWER STRIKE — Directional Momentum + Options Setup Scanner
# Flags stocks with: large move + vol spike + OI buildup at nearest strike
# ══════════════════════════════════════════════════════════════════════════════
_ps_cache = {"data": [], "status": "idle", "updated_at": None, "count": 0}
_ps_lock  = threading.Lock()

def _fetch_option_score(tok, cid, sym_info, spot, direction, nearest_expiry, headers):
    """Fetch option chain for ONE stock — returns score, opt_data, atm_strike, strike_analysis."""
    eq_id = sym_info["security_id"]
    try:
        time.sleep(3)
        r = requests.post(
            f"{DHAN_BASE}/v2/optionchain",
            json={"UnderlyingScrip": int(eq_id), "UnderlyingSeg": "NSE_EQ", "Expiry": nearest_expiry},
            headers=headers, timeout=15
        )
        if r.status_code == 429:
            print(f"[ps-opt] {sym_info['symbol']} 429 — sleeping 6s"); time.sleep(6)
            return 0, {}, None, []
        if r.status_code != 200:
            print(f"[ps-opt] {sym_info['symbol']} {r.status_code}: {r.text[:80]}")
            return 0, {}, None, []

        resp = r.json()
        if resp.get("status") != "success": return 0, {}, None, []
        oc = resp.get("data", {}).get("oc", {})
        if not oc: return 0, {}, None, []

        # Aggregate totals + find ATM
        total_ce_oi = total_pe_oi = total_ce_vol = total_pe_vol = 0
        atm_ce_oi = atm_pe_oi = atm_ce_vol = atm_pe_vol = 0
        atm_ce_prev_oi = atm_pe_prev_oi = 0
        atm_strike = 0; min_diff = float("inf")

        # Collect all strikes for analysis
        strike_rows = []
        for strike_str, sd in oc.items():
            sp   = float(strike_str)
            ce   = sd.get("ce", {}); pe = sd.get("pe", {})
            ce_oi  = int(ce.get("oi", 0)); pe_oi  = int(pe.get("oi", 0))
            ce_vol = int(ce.get("volume", 0)); pe_vol = int(pe.get("volume", 0))
            ce_ltp = float(ce.get("last_price", 0)); pe_ltp = float(pe.get("last_price", 0))
            ce_iv  = float(ce.get("implied_volatility", 0))
            pe_iv  = float(pe.get("implied_volatility", 0))
            ce_delta = float(ce.get("greeks", {}).get("delta", 0))
            pe_delta = float(pe.get("greeks", {}).get("delta", 0))
            ce_gamma = float(ce.get("greeks", {}).get("gamma", 0))
            pe_gamma = float(pe.get("greeks", {}).get("gamma", 0))
            ce_prev_oi = int(ce.get("previous_oi", 0))
            pe_prev_oi = int(pe.get("previous_oi", 0))

            total_ce_oi  += ce_oi;  total_pe_oi  += pe_oi
            total_ce_vol += ce_vol; total_pe_vol += pe_vol

            moneyness = "ATM"
            if direction == "bull":
                if sp < spot * 0.995:  moneyness = "ITM"
                elif sp > spot * 1.005: moneyness = "OTM"
            else:
                if sp > spot * 1.005:  moneyness = "ITM"
                elif sp < spot * 0.995: moneyness = "OTM"

            strike_rows.append({
                "strike": sp, "moneyness": moneyness,
                "ce_ltp": ce_ltp, "pe_ltp": pe_ltp,
                "ce_oi": ce_oi, "pe_oi": pe_oi,
                "ce_vol": ce_vol, "pe_vol": pe_vol,
                "ce_delta": round(ce_delta, 3), "pe_delta": round(pe_delta, 3),
                "ce_gamma": round(ce_gamma, 4), "pe_gamma": round(pe_gamma, 4),
                "ce_iv": round(ce_iv, 1), "pe_iv": round(pe_iv, 1),
                "ce_oi_change": ce_oi - ce_prev_oi,
                "pe_oi_change": pe_oi - pe_prev_oi,
            })

            diff = abs(sp - spot)
            if diff < min_diff:
                min_diff = diff; atm_strike = sp
                atm_ce_oi = ce_oi; atm_pe_oi = pe_oi
                atm_ce_vol = ce_vol; atm_pe_vol = pe_vol
                atm_ce_prev_oi = ce_prev_oi; atm_pe_prev_oi = pe_prev_oi

        pcr = round(total_pe_oi / total_ce_oi, 2) if total_ce_oi else 0
        ce_vol_ratio = round(atm_ce_vol / (atm_ce_oi / 100), 2) if atm_ce_oi else 0
        pe_vol_ratio = round(atm_pe_vol / (atm_pe_oi / 100), 2) if atm_pe_oi else 0
        ce_oi_change = atm_ce_oi - atm_ce_prev_oi
        pe_oi_change = atm_pe_oi - atm_pe_prev_oi

        # Score boost
        opt_score = 0
        if direction == "bull":
            if pcr < 0.7:        opt_score += 2
            if ce_vol_ratio > 5:  opt_score += 1
            if ce_oi_change > 0:  opt_score += 1
        else:
            if pcr > 1.3:        opt_score += 2
            if pe_vol_ratio > 5:  opt_score += 1
            if pe_oi_change > 0:  opt_score += 1

        # Pick best 5 strikes near ATM for popup (2 ITM, ATM, 2 OTM)
        strike_rows.sort(key=lambda x: abs(x["strike"] - spot))
        best_strikes = strike_rows[:5]
        best_strikes.sort(key=lambda x: x["strike"])

        # Find max profit strike — highest delta×gamma ratio near ATM
        # For bull: CE with highest (delta + gamma×10) near spot
        # For bear: PE with highest (abs(delta) + gamma×10) near spot
        best_strike = None
        best_score_opt = -999
        for s in best_strikes:
            if direction == "bull":
                score_opt = s["ce_delta"] + s["ce_gamma"] * 10
                if score_opt > best_score_opt and s["ce_ltp"] > 0:
                    best_score_opt = score_opt; best_strike = s
            else:
                score_opt = abs(s["pe_delta"]) + s["pe_gamma"] * 10
                if score_opt > best_score_opt and s["pe_ltp"] > 0:
                    best_score_opt = score_opt; best_strike = s

        opt_data = {
            "pcr": pcr, "atm_strike": atm_strike,
            "ce_oi": total_ce_oi, "pe_oi": total_pe_oi,
            "atm_ce_oi": atm_ce_oi, "atm_pe_oi": atm_pe_oi,
            "atm_ce_vol": atm_ce_vol, "atm_pe_vol": atm_pe_vol,
            "ce_vol_ratio": ce_vol_ratio, "pe_vol_ratio": pe_vol_ratio,
            "ce_oi_change": ce_oi_change, "pe_oi_change": pe_oi_change,
            "best_strike": best_strike,
            "expiry": nearest_expiry,
        }
        print(f"[ps-opt] {sym_info['symbol']} pcr={pcr} best_strike={best_strike['strike'] if best_strike else 'n/a'} opt_score=+{opt_score}")
        return opt_score, opt_data, atm_strike, best_strikes

    except Exception as e:
        print(f"[ps-opt] {sym_info['symbol']} error: {e}")
        return 0, {}, None, []


def _compute_power_strike(tok):
    """Power Strike — equity filter first, then option chain only for candidates."""
    global _ps_cache
    _ps_cache["status"] = "fetching"
    cid = CREDS.get("client_id", "")

    wait = 0
    while not cache.get("data") and wait < 120:
        print(f"[ps] waiting for screener data... ({wait}s)")
        time.sleep(5); wait += 5
    if not cache.get("data"):
        print(f"[ps] no screener data — aborting")
        _ps_cache["status"] = "idle"; return

    market_open = is_market_open()
    mode = "live" if market_open else "closed"
    headers = {"access-token": tok, "client-id": cid, "Content-Type": "application/json"}
    print(f"[ps] Power Strike scan — mode={mode}...")

    # ── Step 1: Equity filter ─────────────────────────────────────────────────
    candidates = []
    sym_map = {s["symbol"]: s for s in SYMBOLS}

    for row in cache.get("data", []):
        sym       = row["symbol"]
        ltp       = row.get("ltp", 0)
        change    = row.get("change", 0)
        vol_ratio = row.get("volumeRatio", 0)
        mom5d     = row.get("momentum5d", 0)
        today_vol = row.get("todayVol", 0)
        avg_vol   = row.get("avgVol7d", 0)
        if not ltp: continue
        # Relaxed thresholds when market closed — use settled daily data
        chg_min = 1.0 if not market_open else 2.5
        vol_min  = 1.0 if not market_open else 1.5
        if abs(change) < chg_min: continue
        if vol_ratio < vol_min:   continue

        direction = "bull" if change > 0 else "bear"
        momentum_confirms = (direction == "bull" and mom5d > -5) or \
                            (direction == "bear" and mom5d < 5)

        eq_score = 0
        if abs(change) >= 1.0:  eq_score += 1   # any move
        if abs(change) >= 2.5:  eq_score += 1   # decent
        if abs(change) >= 4.0:  eq_score += 1   # strong
        if vol_ratio >= 1.5:    eq_score += 1
        if vol_ratio >= 2.5:    eq_score += 1
        if momentum_confirms:   eq_score += 1
        min_eq = 2 if market_open else 1
        if eq_score < min_eq: continue

        strike_step = 50 if ltp >= 500 else 25 if ltp >= 100 else 10
        atm_base    = round(ltp / strike_step) * strike_step
        atm_strike  = atm_base if ltp < atm_base else atm_base + strike_step if direction == "bull" else atm_base - strike_step
        est_delta   = 0.60 if (ltp > atm_strike if direction=="bull" else ltp < atm_strike) else 0.45

        if market_open:
            setup_note = f"Live: {'+' if change>0 else ''}{change:.2f}% on {vol_ratio:.1f}× vol"
        else:
            setup_note = f"Closed {'+' if change>0 else ''}{change:.2f}% | vol={vol_ratio:.1f}× | 5D={mom5d:.1f}%"

        candidates.append({
            "symbol": sym, "ltp": ltp, "change": change, "direction": direction,
            "volRatio": vol_ratio, "todayVol": today_vol, "avgVol": avg_vol,
            "momentum5d": mom5d, "momentum_ok": momentum_confirms,
            "eq_score": eq_score, "score": eq_score,
            "signal_strength": "strong" if eq_score >= 4 else "moderate",
            "atm_strike": atm_strike, "est_delta": est_delta,
            "mode": mode, "setup_note": setup_note, "strategy": "Power Strike",
            "action": f"Buy {atm_strike} {'CE' if direction=='bull' else 'PE'}" if atm_strike else "—",
            "opt_data": {}, "opt_score": 0,
            "signal_time": ist_now().strftime("%H:%M IST"),  # timestamp when detected
            "strikes": [],  # will be populated after option chain fetch
        })

    print(f"[ps] equity filter: {len(candidates)} candidates — now fetching option chains...")
    _ps_cache["status"] = f"fetching options for {len(candidates)} stocks..."

    # ── Step 2: Get nearest expiry once ───────────────────────────────────────
    nearest_expiry = None
    if candidates:
        for c in candidates[:5]:
            si = sym_map.get(c["symbol"])
            if not si: continue
            try:
                r = requests.post(f"{DHAN_BASE}/v2/optionchain/expirylist",
                                  json={"UnderlyingScrip": int(si["security_id"]), "UnderlyingSeg": "NSE_EQ"},
                                  headers=headers, timeout=10)
                time.sleep(3)
                if r.status_code == 200:
                    dates = r.json().get("data", [])
                    if dates:
                        nearest_expiry = dates[0]
                        print(f"[ps] expiry: {nearest_expiry}")
                        break
            except: continue

    # ── Step 3: Fetch option chain only for candidates ─────────────────────────
    if nearest_expiry:
        for c in candidates:
            si = sym_map.get(c["symbol"])
            if not si: continue
            opt_score, opt_data, opt_atm, best_strikes = _fetch_option_score(
                tok, cid, si, c["ltp"], c["direction"], nearest_expiry, headers)
            c["opt_score"]  = opt_score
            c["opt_data"]   = opt_data
            c["strikes"]    = best_strikes
            c["score"]      = c["eq_score"] + opt_score
            c["signal_strength"] = "strong" if c["score"] >= 6 else "moderate" if c["score"] >= 3 else "weak"
            if opt_data:
                pcr = opt_data.get("pcr", 0)
                cvr = opt_data.get("ce_vol_ratio", 0)
                pvr = opt_data.get("pe_vol_ratio", 0)
                opt_label = f"PCR={pcr} | {'CE' if c['direction']=='bull' else 'PE'} vol={cvr if c['direction']=='bull' else pvr:.1f}×"
                c["setup_note"] = c["setup_note"] + f" | {opt_label}"
                if opt_atm: c["atm_strike"] = opt_atm
                # Use best strike from delta/gamma analysis
                best = opt_data.get("best_strike")
                if best:
                    opt_type = "CE" if c["direction"] == "bull" else "PE"
                    c["best_strike"] = best["strike"]
                    c["best_ltp"]    = best["ce_ltp"] if c["direction"] == "bull" else best["pe_ltp"]
                    c["best_delta"]  = best["ce_delta"] if c["direction"] == "bull" else best["pe_delta"]
                    c["best_gamma"]  = best["ce_gamma"] if c["direction"] == "bull" else best["pe_gamma"]
                    c["best_iv"]     = best["ce_iv"] if c["direction"] == "bull" else best["pe_iv"]
                    c["action"] = f"Buy {best['strike']} {opt_type} @ ₹{best['ce_ltp'] if c['direction']=='bull' else best['pe_ltp']}"
    else:
        print(f"[ps] could not get expiry — skipping option enrichment")

    results = sorted(candidates, key=lambda x: (x["score"], abs(x["change"])), reverse=True)
    _ps_cache.update({
        "data": results, "status": "ok",
        "updated_at": ist_now().strftime("%H:%M:%S IST"),
        "count": len(results),
        "bulls": len([r for r in results if r["direction"]=="bull"]),
        "bears": len([r for r in results if r["direction"]=="bear"]),
        "market_open": market_open, "mode": mode,
    })
    print(f"[ps] done — {len(results)} signals | mode={mode}")

# ── Next Day Watchlist ─────────────────────────────────────────────────────────
_nd_cache = {"data": [], "status": "idle", "updated_at": None, "count": 0}
_nd_lock  = threading.Lock()

def _compute_next_day(tok):
    """Next Day — stocks aligned for tomorrow based on today's closed data."""
    global _nd_cache
    _nd_cache["status"] = "fetching"

    wait = 0
    while not cache.get("data") and wait < 120:
        print(f"[nd] waiting for screener data... ({wait}s)")
        time.sleep(5); wait += 5
    if not cache.get("data"):
        print(f"[nd] no screener data — aborting")
        _nd_cache["status"] = "idle"; return

    print(f"[nd] Next Day scan starting...")
    results = []

    for row in cache.get("data", []):
        sym       = row["symbol"]
        ltp       = row.get("ltp", 0)
        change    = row.get("change", 0)
        vol_ratio = row.get("volumeRatio", 0)
        mom5d     = row.get("momentum5d", 0)
        today_vol = row.get("todayVol", 0)
        avg_vol   = row.get("avgVol7d", 0)
        if not ltp: continue

        # Next Day filters — relaxed when market closed
        _mo = is_market_open()
        chg_min_nd = 1.0 if not _mo else 2.0
        vol_min_nd  = 1.0 if not _mo else 1.5
        if abs(change) < chg_min_nd: continue
        if vol_ratio < vol_min_nd:   continue
        if abs(change) > 8.0: continue

        direction = "bull" if change > 0 else "bear"

        if _mo:
            mom_aligned = (direction == "bull" and mom5d >= 0) or \
                          (direction == "bear" and mom5d <= 0)
            if not mom_aligned: continue

        score = 0
        if abs(change) >= 2.0:   score += 1
        if abs(change) >= 3.5:   score += 1
        if vol_ratio >= 2.0:     score += 1
        if vol_ratio >= 3.0:     score += 1
        if abs(mom5d) >= 3.0:    score += 1  # strong 5D alignment
        if score < 2: continue

        # Risk level for tomorrow's entry
        risk = "HIGH" if abs(change) >= 6 else "MED" if abs(change) >= 4 else "LOW"

        # Slightly OTM strike for next-day entry (better R:R than ITM)
        strike_step = 50 if ltp >= 500 else 25 if ltp >= 100 else 10
        atm_base    = round(ltp / strike_step) * strike_step
        if direction == "bull":
            atm_strike = atm_base + strike_step  # one step OTM CE
        else:
            atm_strike = atm_base - strike_step  # one step OTM PE
        est_delta = 0.40  # OTM entry

        print(f"[nd] {sym} dir={direction} chg={change:.2f}% vol={vol_ratio:.1f}x score={score} risk={risk}")
        results.append({
            "symbol": sym, "ltp": ltp, "change": change, "direction": direction,
            "volRatio": vol_ratio, "todayVol": today_vol, "avgVol": avg_vol,
            "momentum5d": mom5d, "score": score,
            "signal_strength": "strong" if score >= 4 else "moderate",
            "atm_strike": atm_strike, "est_delta": est_delta, "risk": risk,
            "setup_note": f"Closed {'+' if change>0 else ''}{change:.2f}% | 5D={mom5d:.1f}% | Risk={risk}",
            "action": f"Tomorrow: Buy {atm_strike} {'CE' if direction=='bull' else 'PE'}" if atm_strike else "—",
        })

    results.sort(key=lambda x: (x["score"], abs(x["change"])), reverse=True)
    _nd_cache.update({
        "data": results, "status": "ok",
        "updated_at": ist_now().strftime("%H:%M:%S IST"),
        "count": len(results),
        "bulls": len([r for r in results if r["direction"]=="bull"]),
        "bears": len([r for r in results if r["direction"]=="bear"]),
        "market_open": is_market_open(),
    })
    print(f"[nd] done — {len(results)} next-day signals")

def _run_nd_locked(tok):
    with _nd_lock: _compute_next_day(tok)

def _nd_stale():
    last = _nd_cache.get("updated_at")
    if not last: return True
    try:
        t = datetime.strptime(last, "%H:%M:%S IST").replace(
            year=ist_now().year, month=ist_now().month, day=ist_now().day, tzinfo=IST)
        return (ist_now() - t).seconds > 300
    except: return True

@app.get("/api/nextday")
def get_next_day(x_client_id:str=Header(None), x_access_token:str=Header(None),
                 refresh:bool=Query(False)):
    cid = x_client_id or CREDS.get("client_id","")
    tok = x_access_token or CREDS.get("access_token","")
    if not cid or not tok: return {"status":"no_credentials","data":[]}
    CREDS["client_id"]=cid; CREDS["access_token"]=tok
    should_run = (refresh or _nd_stale()) and not _nd_lock.locked()
    if should_run:
        threading.Thread(target=_run_nd_locked, args=(tok,), daemon=True).start()
    return _nd_cache

def _run_ps_locked(tok):
    with _ps_lock: _compute_power_strike(tok)

def _ps_stale():
    last = _ps_cache.get("updated_at")
    if not last: return True
    try:
        t = datetime.strptime(last, "%H:%M:%S IST").replace(
            year=ist_now().year, month=ist_now().month, day=ist_now().day, tzinfo=IST)
        return (ist_now() - t).seconds > 300
    except: return True

@app.get("/api/powerstrike")
def get_power_strike(x_client_id:str=Header(None), x_access_token:str=Header(None),
                     refresh:bool=Query(False)):
    cid = x_client_id or CREDS.get("client_id","")
    tok = x_access_token or CREDS.get("access_token","")
    if not cid or not tok: return {"status":"no_credentials","data":[]}
    CREDS["client_id"]=cid; CREDS["access_token"]=tok
    should_run = (refresh or _ps_stale()) and not _ps_lock.locked()
    if should_run:
        threading.Thread(target=_run_ps_locked, args=(tok,), daemon=True).start()
    return _ps_cache

@app.get("/api/powerstrike/bull")
def ps_bull(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    return {"data":[x for x in _ps_cache["data"] if x["direction"]=="bull"]}

@app.get("/api/powerstrike/bear")
def ps_bear(x_client_id:str=Header(None),x_access_token:str=Header(None)):
    return {"data":[x for x in _ps_cache["data"] if x["direction"]=="bear"]}


# ══════════════════════════════════════════════════════════════════════════════
# OI STRATEGY — 5-Factor ITM Options Scanner
# Based on verified Sensibull trades (Mar 2026):
#
#   Stock         Spot     Strike  Type  P&L
#   TATASTEEL     196.73   190     PE   +17,160  (Short Buildup, stock near 190)
#   MAZDOCK      2352.50  2300     CE   +21,930  (Long Buildup, broke 2300)
#   JINDALSTEL   1143.30  1150     PE   +18,750  (Short Buildup, stock < 1150)
#   BANDHANBNK    162.54   170     PE   +15,120  (Short Buildup, stock < 170)
#   NATIONALUM    395.15   390     CE   +20,250  (Long Buildup, broke 390)
#   JSWSTEEL     1168.00  1150     CE   +20,587  (Long Buildup, broke 1150)
#   ONGC          270.80   280     PE   +16,425  (Short Buildup, stock < 280)
#   HAVELLS      1358.00  1400     CE   +16,500  (CE sell, stock < 1400)
#   COLPAL       2055.60  2000     PE    -2,936  (FMCG — avoid!)
#
# 5-Factor Scoring (100 pts total):
#   1. OI Buildup       25 pts  — futures OI change ≥15% aligned with direction
#   2. ITM Strike       20 pts  — 1 step ITM → delta ~0.65+
#   3. Sector + Move    20 pts  — ≥2.5% move, not FMCG/Pharma
#   4. PCR + OI Change  20 pts  — PCR aligned, ATM OI change positive
#   5. Vol Confirmation 15 pts  — vol ratio ≥1.5×
#
# Score ≥75 = High Probability  |  50-74 = Moderate  |  <50 = Filtered out
# ══════════════════════════════════════════════════════════════════════════════

# Sector classification — Metal/PSU/Banking respond best to OI signals
# FMCG/Pharma are defensive — avoid for directional PE buys (see COLPAL loss)
_OIS_SECTOR_MAP = {
    "TATASTEEL":"Metal","JSWSTEEL":"Metal","JINDALSTEL":"Metal","SAIL":"Metal",
    "NATIONALUM":"Metal","HINDALCO":"Metal","VEDL":"Metal","NMDC":"Metal",
    "APLAPOLLO":"Metal","WELCORP":"Metal","RATNAMANI":"Metal",
    "ONGC":"PSU-Oil","BPCL":"PSU-Oil","IOC":"PSU-Oil","GAIL":"PSU-Oil",
    "MAZDOCK":"Defence","BEL":"Defence","HAL":"Defence","COCHINSHIP":"Defence",
    "GRSE":"Defence","BEML":"Defence",
    "BANDHANBNK":"Banking","IDFCFIRSTB":"Banking","RBLBANK":"Banking",
    "PNB":"Banking","BANKBARODA":"Banking","CANBK":"Banking",
    "HDFCBANK":"Banking","ICICIBANK":"Banking","AXISBANK":"Banking",
    "KOTAKBANK":"Banking","SBIN":"Banking","FEDERALBNK":"Banking",
    "TATATECH":"IT","TCS":"IT","INFY":"IT","WIPRO":"IT",
    "HCLTECH":"IT","MPHASIS":"IT","LTIM":"IT","TECHM":"IT",
    "COLPAL":"FMCG","HINDUNILVR":"FMCG","ITC":"FMCG","BRITANNIA":"FMCG",
    "NESTLEIND":"FMCG","DABUR":"FMCG","MARICO":"FMCG","GODREJCP":"FMCG",
    "TATACONSUM":"FMCG","EMAMILTD":"FMCG",
    "SUNPHARMA":"Pharma","DRREDDY":"Pharma","CIPLA":"Pharma",
    "DIVISLAB":"Pharma","AUROPHARMA":"Pharma","ALKEM":"Pharma",
    "HAVELLS":"Consumer","VGUARD":"Consumer","POLYCAB":"Consumer",
    "CROMPTON":"Consumer","VOLTAS":"Consumer",
}
_OIS_AVOID_BEAR  = set()   # no sector exclusions
_OIS_AVOID_BULL  = set()   # no sector exclusions
_OIS_SCORE_MIN   = 50                   # filter threshold
_OIS_SCORE_HIGH  = 75                   # high-probability threshold

_ois_cache = {
    "data": [], "status": "idle", "updated_at": None,
    "count": 0, "bulls": 0, "bears": 0, "strong": 0, "market_open": False,
}
_ois_lock = threading.Lock()


def _ois_strike_step(spot: float) -> int:
    """Standard NSE strike interval for a given spot price."""
    if spot >= 5000: return 200
    if spot >= 2000: return 100
    if spot >= 500:  return 50
    if spot >= 200:  return 25
    if spot >= 100:  return 10
    return 5


def _ois_itm_strike(spot: float, direction: str) -> dict:
    """
    Select 1-strike ITM for maximum delta (~0.65).

    Bull (CE buy): strike BELOW spot → stock already above strike → ITM CE
      e.g. JSWSTEEL 1168 → 1150 CE  (1168 > 1150 → ITM ✓, delta ~0.68)
      e.g. MAZDOCK 2352 → 2300 CE   (2352 > 2300 → ITM ✓, delta ~0.70)

    Bear (PE buy): strike ABOVE spot → stock already below strike → ITM PE
      e.g. BANDHANBNK 162 → 170 PE  (162 < 170 → ITM ✓, delta ~0.68)
      e.g. JINDALSTEL 1143 → 1150 PE (1143 < 1150 → ITM ✓, delta ~0.65)
      e.g. ONGC 270 → 280 PE        (270 < 280 → ITM ✓, delta ~0.67)
    """
    step  = _ois_strike_step(spot)
    base  = round(spot / step) * step

    if direction == "bull":
        strike    = base - step          # one step below → ITM CE
        is_itm    = spot > strike
    else:
        strike    = base + step          # one step above → ITM PE
        is_itm    = spot < strike

    return {
        "strike":    int(strike),
        "opt_type":  "CE" if direction == "bull" else "PE",
        "moneyness": "ITM" if is_itm else "ATM",
        "delta_est": 0.68 if is_itm else 0.50,
        "step":      step,
    }


def _ois_compute_score(row: dict, opt_data: dict) -> int:
    """
    5-Factor OI Strategy Score (0–100).
    Derived from analysis of all 10 Sensibull verified trades.
    """
    score     = 0
    direction = row.get("direction", "bull")
    sym       = row.get("symbol", "")
    sector    = _OIS_SECTOR_MAP.get(sym, "Unknown")
    change    = abs(row.get("change", 0))
    vol_ratio = row.get("volRatio", 0)
    pcr       = opt_data.get("pcr", 0)
    ce_oi_chg = opt_data.get("ce_oi_change", 0)
    pe_oi_chg = opt_data.get("pe_oi_change", 0)
    ce_vr     = opt_data.get("ce_vol_ratio", 0)
    pe_vr     = opt_data.get("pe_vol_ratio", 0)
    opt_score = row.get("opt_score", 0)

    # ── Factor 1: OI Buildup (25 pts) ──────────────────────────────────────
    # Long Buildup (OI↑ + Price↑) → CE   |  Short Buildup (OI↑ + Price↓) → PE
    oi_ok = (
        (direction == "bull" and (opt_score > 0 or ce_oi_chg > 0 or ce_vr > 3)) or
        (direction == "bear" and (opt_score > 0 or pe_oi_chg > 0 or pe_vr > 3))
    )
    if oi_ok:
        score += 25
    elif row.get("eq_score", 0) >= 2:
        score += 10   # partial credit for strong equity signal alone

    # ── Factor 2: ITM Strike (20 pts) ──────────────────────────────────────
    spot = row.get("ltp", 0)
    itm  = _ois_itm_strike(spot, direction)
    score += 20 if itm["moneyness"] == "ITM" else 8

    # ── Factor 3: Sector + Move Size (20 pts) ──────────────────────────────
    # Factor 3: all sectors included
    if change >= 4.0:    score += 20
    elif change >= 2.5:  score += 15
    elif change >= 1.5:  score += 10

    # ── Factor 4: PCR + OI Change Alignment (20 pts) ──────────────────────
    if direction == "bull":
        if 0 < pcr < 0.75:   score += 10   # low PCR = CE heavy = bullish
        if ce_oi_chg > 0:     score += 10   # CE OI building = longs entering
    else:
        if pcr > 1.25:        score += 10   # high PCR = PE heavy = bearish
        if pe_oi_chg > 0:     score += 10   # PE OI building = shorts entering

    # ── Factor 5: Volume Confirmation (15 pts) ─────────────────────────────
    if vol_ratio >= 2.0:    score += 15
    elif vol_ratio >= 1.5:  score += 10
    elif vol_ratio >= 1.2:  score +=  5

    return min(score, 100)


def _compute_ois(tok: str):
    """
    OI Strategy Scanner.
    Waits for Power Strike data (which already fetched option chains),
    then applies 5-factor scoring + forces ITM strike selection.
    No extra Dhan API calls needed — reuses _ps_cache data.
    """
    global _ois_cache
    _ois_cache["status"] = "fetching"
    market_open = is_market_open()
    print(f"[ois] starting OI Strategy scan... market_open={market_open}")

    source_data = []

    if market_open:
        # Live market: wait for Power Strike which has option chain data
        wait = 0
        while not _ps_cache.get("data") and wait < 180:
            print(f"[ois] waiting for Power Strike data... ({wait}s)")
            time.sleep(5); wait += 5
        source_data = _ps_cache.get("data", [])
        if not source_data:
            print(f"[ois] no PS data live — using screener cache")

    # Closed market OR live fallback — build from screener cache directly
    # Lower thresholds: settled daily data, not intraday spikes
    if not source_data:
        chg_min = 0.5 if not market_open else 1.5
        vol_min  = 0.5 if not market_open else 1.2
        for row in cache.get("data", []):
            chg = row.get("change", 0)
            vr  = row.get("volumeRatio", 0)
            ltp = row.get("ltp", 0)
            if not ltp: continue
            if abs(chg) < chg_min: continue
            if vr < vol_min: continue
            source_data.append({
                **row,
                "direction":  "bull" if chg > 0 else "bear",
                "opt_data":   {},
                "opt_score":  0,
                "eq_score":   2 if abs(chg) >= 2.5 else 1,
                "strikes":    [],
                "volRatio":   vr,
            })
        print(f"[ois] screener fallback: {len(source_data)} candidates")
    print(f"[ois] scoring {len(source_data)} candidates...")
    results = []

    for row in source_data:
        sym      = row.get("symbol", "")
        spot     = row.get("ltp", 0)
        if not spot: continue

        direction = row.get("direction", "bull")
        opt_data  = row.get("opt_data") or {}
        sector    = _OIS_SECTOR_MAP.get(sym, "Unknown")

        score = _ois_compute_score(row, opt_data)
        if score < _OIS_SCORE_MIN: continue

        # Force 1-strike ITM selection (core of the strategy)
        itm      = _ois_itm_strike(spot, direction)
        opt_type = itm["opt_type"]

        # Prefer option-chain derived best_strike only if it's actually ITM
        bs        = row.get("best_strike") or itm["strike"]
        bl        = row.get("best_ltp", 0)
        bd        = row.get("best_delta") or itm["delta_est"]
        bg        = row.get("best_gamma", 0)
        biv       = row.get("best_iv", 0)
        bs_is_itm = (direction == "bull" and bs < spot) or (direction == "bear" and bs > spot)
        if not bs_is_itm:
            # Override: always use ITM strike, not whatever PS selected
            bs = itm["strike"]; bd = itm["delta_est"]; bl = 0

        pcr      = opt_data.get("pcr", 0)
        ce_oi_ch = opt_data.get("ce_oi_change", 0)
        pe_oi_ch = opt_data.get("pe_oi_change", 0)

        # Human-readable OI signal label
        if direction == "bull":
            oi_label = ("Long Buildup" if ce_oi_ch > 0 else
                        "Short Covering" if (0 < pcr < 0.8) else "CE Surge")
        else:
            oi_label = ("Short Buildup" if pe_oi_ch > 0 else
                        "Long Unwinding" if pcr > 1.2 else "PE Surge")

        strength = "strong" if score >= _OIS_SCORE_HIGH else "moderate"
        vr       = row.get("volRatio", 0)

        # Build strategy note
        parts = [
            f"{'+' if row.get('change',0)>0 else ''}{row.get('change',0):.1f}%",
            f"vol={vr:.1f}x",
            f"{oi_label}",
            f"sector={sector}",
        ]
        if pcr: parts.append(f"PCR={pcr:.2f}")
        setup_note = " | ".join(parts)

        # 5-factor flags for frontend scorecard
        factors = {
            "oi_buildup":       score >= 25,
            "itm_strike":       itm["moneyness"] == "ITM",
            "sector_momentum":  abs(row.get("change", 0)) >= 2.5,
            "pcr_aligned":      (direction == "bull" and 0 < pcr < 0.8) or
                                (direction == "bear" and pcr > 1.2),
            "vol_confirmed":    vr >= 1.5,
        }

        results.append({
            # Core price fields
            "symbol":       sym,
            "ltp":          spot,
            "change":       row.get("change", 0),
            "direction":    direction,
            "sector":       sector,
            "volRatio":     vr,
            "todayVol":     row.get("todayVol", 0),
            "avgVol":       row.get("avgVol", 0),
            "momentum5d":   row.get("momentum5d", 0),
            # ITM Strike recommendation
            "itm_strike":   bs,          # the recommended ITM strike
            "itm_ltp":      bl,          # option LTP (0 if unavailable)
            "itm_delta":    bd,          # delta at that strike
            "itm_gamma":    bg,
            "itm_iv":       biv,
            "itm_type":     opt_type,    # "CE" or "PE"
            "itm_moneyness":itm["moneyness"],
            "action":       f"Buy {bs} {opt_type}{' @ ₹'+str(round(bl,1)) if bl else ''}",
            # OI data
            "oi_signal":    oi_label,
            "opt_data":     opt_data,
            "opt_score":    row.get("opt_score", 0),
            "eq_score":     row.get("eq_score", 0),
            "strikes":      row.get("strikes", []),  # near-ATM chain for popup
            # Scoring
            "ois_score":        score,
            "signal_strength":  strength,
            "setup_note":       setup_note,
            "signal_time":      row.get("signal_time", ist_now().strftime("%H:%M IST")),
            "factors":          factors,
            "expiry":           opt_data.get("expiry", ""),
        })

    results.sort(key=lambda x: (x["ois_score"], abs(x["change"])), reverse=True)
    _ois_cache.update({
        "data":        results,
        "status":      "ok",
        "updated_at":  ist_now().strftime("%H:%M:%S IST"),
        "count":       len(results),
        "bulls":       sum(1 for r in results if r["direction"] == "bull"),
        "bears":       sum(1 for r in results if r["direction"] == "bear"),
        "strong":      sum(1 for r in results if r["ois_score"] >= _OIS_SCORE_HIGH),
        "market_open": is_market_open(),
        "mode":        "live" if is_market_open() else "closed",
    })
    print(f"[ois] done — {len(results)} signals "
          f"({_ois_cache['bulls']} bull, {_ois_cache['bears']} bear, "
          f"{_ois_cache['strong']} strong ≥{_OIS_SCORE_HIGH})")


def _run_ois_locked(tok: str):
    with _ois_lock: _compute_ois(tok)


def _ois_stale() -> bool:
    last = _ois_cache.get("updated_at")
    if not last: return True
    try:
        t = datetime.strptime(last, "%H:%M:%S IST").replace(
            year=ist_now().year, month=ist_now().month, day=ist_now().day, tzinfo=IST)
        return (ist_now() - t).seconds > 300
    except:
        return True


@app.get("/api/oistrategy")
def get_ois(x_client_id: str = Header(None), x_access_token: str = Header(None),
            refresh: bool = Query(False)):
    """
    OI Strategy Scanner — picks ITM strikes using 5-factor OI scoring.
    Reuses Power Strike option chain data. No extra API calls.
    Score ≥75 = high probability  |  50-74 = moderate
    """
    cid = x_client_id or CREDS.get("client_id", "")
    tok = x_access_token or CREDS.get("access_token", "")
    if not cid or not tok: return {"status": "no_credentials", "data": []}
    CREDS["client_id"] = cid; CREDS["access_token"] = tok

    should_run = (refresh or _ois_stale()) and not _ois_lock.locked()
    if should_run:
        # Ensure Power Strike has run first (provides option chain data)
        if not _ps_cache.get("data") and not _ps_lock.locked():
            print(f"[ois] triggering Power Strike first for option data...")
            threading.Thread(target=_run_ps_locked, args=(tok,), daemon=True).start()
        threading.Thread(target=_run_ois_locked, args=(tok,), daemon=True).start()
    return _ois_cache


@app.get("/api/oistrategy/bull")
def ois_bull(x_client_id: str = Header(None), x_access_token: str = Header(None)):
    """Bullish OI setups — ITM CE buys with Long Buildup signal."""
    return {"data": [x for x in _ois_cache["data"] if x["direction"] == "bull"]}


@app.get("/api/oistrategy/bear")
def ois_bear(x_client_id: str = Header(None), x_access_token: str = Header(None)):
    """Bearish OI setups — ITM PE buys with Short Buildup signal."""
    return {"data": [x for x in _ois_cache["data"] if x["direction"] == "bear"]}


@app.get("/api/oistrategy/strong")
def ois_strong():
    """High-probability setups only (score ≥75)."""
    return {"data": [x for x in _ois_cache["data"] if x["ois_score"] >= _OIS_SCORE_HIGH]}
